WebExam2/Notes/urls.py
from django.urls import path

from WebExam2.Notes.views import home_page, add_note, edit_note, delete_note, details_note, profile_page, delete_profile

urlpatterns = (
    path('', home_page, name='index'),
    path('add/', add_note, name='add'),
    path('edit/<int:id>/', edit_note, name='edit'),
    path('delete/<int:id>/', delete_note, name='delete'),
    path('details/<int:id>/', details_note, name='details'),
    path('profile/', profile_page, name='profile'),
    path('profile/delete', delete_profile, name='delete-profile'),
)

WebExam2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebExam2.Notes.urls')),
]

WebExam2/Notes/models.py
from django.db import models


# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(
        max_length=20,
    )

    last_name = models.CharField(
        max_length=20,
    )

    age = models.IntegerField()

    image_url = models.URLField()


class Note(models.Model):
    title = models.CharField(
        max_length=30,
    )

    content = models.TextField()

    image_url = models.URLField()

WebExam2/Notes/forms.py
from django.forms import ModelForm

from WebExam2.Notes.models import Profile, Note


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'


class DeleteNoteForm(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['disabled'] = True

    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance


# class DeleteProfileForm(ModelForm):
#     class Meta:
#         model = Profile
#         fields = '__all__'
#
#     def save(self, commit=True):
#         if commit:
#             self.instance.delete()
#         return self.instance

WebExam2/Notes/views.py
from django.shortcuts import render, redirect

from WebExam2.Notes.forms import ProfileForm, NoteForm, DeleteNoteForm
from WebExam2.Notes.models import Profile, Note


# Create your views here.
def home_page(request):
    profile = Profile.objects.first()
    notes = Note.objects.all()

    form = ProfileForm()
    if not profile:
        form = ProfileForm()
        if request.method == "POST":
            form = ProfileForm(request.POST)
            if form.is_valid():
                form.save()
                return render(request, 'home-with-profile.html')

        context = {
            'form': form,
            'profile': profile,
        }

        return render(request, 'home-no-profile.html', context)

    context = {
        'form': form,
        'notes': notes,

    }

    return render(request, 'home-with-profile.html', context)


def add_note(request):
    if request.method == "GET":
        form = NoteForm()
    else:
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form': form,
    }

    return render(request, 'note-create.html', context)


def edit_note(request, id):
    note = Note.objects.filter(pk=id).get()
    if request.method == "GET":
        form = NoteForm(instance=note)
    else:
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form': form,
        'note': note,
    }

    return render(request, 'note-edit.html', context)


def delete_note(request, id):
    note = Note.objects.filter(pk=id).get()

    if request.method == "GET":
        form = DeleteNoteForm(instance=note)
    else:
        form = DeleteNoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form': form,
        'note': note,
    }

    return render(request, 'note-delete.html', context)


def details_note(request, id):
    note = Note.objects.filter(pk=id).get()

    context = {
        'note': note,
    }

    return render(request, 'note-details.html', context)


def profile_page(request):
    profile = Profile.objects.get()
    notes = Note.objects.all()
    form = ProfileForm()

    # if request.method == "POST":
    #     form = DeleteProfileForm(request.POST, instance=profile)
    #     if form.is_valid():
    #         notes.delete()
    #         form.save()
    #         return redirect('index')

    context = {
        'form': form,
        'profile': profile,
        'notes': notes,
    }

    return render(request, 'profile.html', context)


def delete_profile(request):
    user_profile = Profile.objects.first()
    all_notes = Note.objects.all()

    user_profile.delete()
    all_notes.delete()
    return redirect('index')

templates/base/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" width="32" height="32" /></li>

                    <li><a href="{% url 'index' %}">Notes</a></li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->
{% block page_content %}
{% endblock page_content %}
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

templates/home-no-profile.html
{% extends 'base/base.html' %}
{% block page_content %}
 <div class="body">
            <!--headings-->
            <h1>Enter Your Data</h1>
            <!--end headings-->

            <!--profile data form-->
            <div class="form">
                <form method="POST">
                 {% csrf_token %}
                    {{ form }}

{#                    <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0" />#}
{#                    <label for="firstName">First Name</label>#}
{#                    <input type="text" name="first_name" maxlength="15" required="" id="id_first_name" />#}
{##}
{#                    <label for="lastName">Last Name</label>#}
{#                    <input type="text" name="last_name" maxlength="15" required="" id="id_last_name" />#}
{##}
{#                    <label for="age">Age</label>#}
{#                    <input type="number" name="age" required="" id="id_age" />#}
{##}
{#                    <label for="profilePhoto">Link to Profile Image</label>#}
{#                    <input type="url" name="profile_image" required="" id="id_image" />#}

                    <input type="submit" value="SUBMIT" />


                </form>
            </div>
            <!--end profile data form-->
        </div>
{% endblock page_content %}

templates/home-with-profile.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <h1>My Notes</h1>

        {% if not notes %}
        <h2>There are no notes.</h2>
        <!--notes container-->
            {% else %}
            {% for note in notes %}
        <div class="note-container">
            <h2>{{ note.title }} <img src="{{ note.image_url }}" /></h2>

            <div class="right">
                <a class="button details" href="{% url 'details' note.id %}">Details</a>
                <a class="button edit" href="{% url 'edit' note.id %}">Edit</a>
                <a class="button delete" href="{% url 'delete' note.id %}">Delete</a>
            </div>
        </div>

{#        <div class="note-container">#}
{#            <h2>Python Web Basics <img src="https://about.softuni.bg/Content/images/home-page/softuni-logo.svg" /></h2>#}
{##}
{#            <div class="right">#}
{#                <a class="button details" href="/details/4">Details</a>#}
{#                <a class="button edit" href="/edit/4">Edit</a>#}
{#                <a class="button delete" href="/delete/4">Delete</a>#}
{#            </div>#}
{#        </div>#}
            {% endfor %}
            {% endif %}

        <!--end notes container-->

        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

templates/note-create.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right"><a href="{% url 'profile' %}">Profile</a></li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Add Note</h1>
            <!--headings-->

            <!--note data form-->
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" maxlength="200" required="" id="id_image_url" />#}
{##}
                    <input type="submit" value="Publish" />
                </form>
            </div>
            <!--end note data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

templates/note-delete.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Delete Note</h1>
            <!--headings-->

            <!--note delete data form-->
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" disabled="" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">#}
{#Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.#}
{##}
{#                    </textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" disabled="" required="" id="id_image_url" />#}

                    <input type="submit" value="Delete" />
                </form>
            </div>
            <!--end note delete data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

templates/note-details.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Note Details</h1>
            <!--headings-->

            <!--details note box-->
            <div class="note-details-container">
                <h2>Today's Tasks</h2>
                <img class="detail-img" src="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" alt="note-image" />
                <div>
                    <p>Content</p>
                </div>
                <p>
                    {{ note.content }}
                </p>
                <div class="right">
                    <a class="button edit" href="{% url 'edit' note.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' note.id %}">Delete</a>
                </div>
            </div>
            <!--end details note box-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

templates/note-edit.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Edit Note</h1>
            <!--headings-->

            <!--note edit data form-->
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description">Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.</textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" required="" id="id_image_url" />#}

                    <input type="submit" value="Edit" />
                </form>
            </div>
            <!--end note edit data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

templates/profile.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Your Profile</h1>
            <!--end headings-->

            <!--profile details container TODO-->

            <div class="note-container">
                <h2>
                    {{ profile.first_name }} {{ profile.last_name }}
                    <img src="{{ profile.image_url }}" />
                </h2>
                <p>{{ profile.age }}</p>
                <div>
                    <p>All notes: {{ notes.count }}</p>
                </div>
                <div class="right">
                    <a class="button delete" href="{% url 'delete-profile' %}">Delete</a>

                </div>
            </div>
            <!--end profile details container-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>